steps:
  - group: Build and Test
    steps:
    - command: zig build test


  - group: Crosscompile
    steps:
    - label: "Target: {{matrix.target}} :zap:"
      command: "zig build -Dtarget={{matrix.target}}"
      matrix:
        setup:
          target:
          - "aarch64-linux-gnu"
          - "aarch64-linux-musl"
          - "aarch64-macos"
          - "x86-linux-gnu"
          - "x86-linux-musl"
            # TODO: when _tls_index is fixed
            #- "x86-windows"
          - "x86_64-linux-gnu"
          - "x86_64-linux-musl"
          - "x86_64-macos"
          - "x86_64-windows-gnu"
